FROM node:latest

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
ADD angular.json /usr/src/app/angular.json
ADD package.json /usr/src/app/package.json
RUN npm install
RUN ng -v
# -- for some reason installed version of typescript is 2.9.2
